-- Supabase SQL Schema for Vanguard Invest

-- Vanguard Invest Complete Reset Script
-- WARNING: This will delete all existing data

-- Drop existing tables if they exist
DROP TABLE IF EXISTS active_plans CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS investment_plans CASCADE;
DROP TABLE IF EXISTS settings CASCADE;

-- 1. Users Table (Profile)
CREATE TABLE users (
  id UUID PRIMARY KEY, -- Matches Supabase Auth UID
  email TEXT UNIQUE NOT NULL,
  balance DECIMAL DEFAULT 0,
  referral_code TEXT UNIQUE NOT NULL,
  referred_by TEXT,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Investment Plans Table
CREATE TABLE investment_plans (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  min_investment DECIMAL NOT NULL,
  duration_days INTEGER NOT NULL,
  profit_percentage DECIMAL NOT NULL,
  color TEXT NOT NULL
);

-- 3. Transactions Table
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- 'deposit', 'withdrawal', 'investment', 'profit', 'bonus'
  amount DECIMAL NOT NULL,
  status TEXT NOT NULL, -- 'pending', 'completed', 'failed'
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Active Plans Table
CREATE TABLE active_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  plan_name TEXT NOT NULL,
  amount DECIMAL NOT NULL,
  profit_rate DECIMAL NOT NULL,
  duration_days INTEGER NOT NULL,
  start_date TIMESTAMPTZ DEFAULT NOW(),
  end_date TIMESTAMPTZ NOT NULL
);

-- 5. Settings Table
CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Seed Initial Data
INSERT INTO investment_plans (id, name, min_investment, duration_days, profit_percentage, color) VALUES
('starter', 'Starter VIP', 50, 7, 10, 'bg-blue-500'),
('pro', 'Pro VIP', 500, 14, 25, 'bg-indigo-600'),
('elite', 'Elite VIP', 2000, 30, 60, 'bg-emerald-600'),
('whale', 'Whale VIP', 10000, 90, 200, 'bg-amber-500');

INSERT INTO settings (key, value) VALUES
('usdt_address', 'TF3kH28vsP7we5LKk7VoUjh1jZfyXXWCQr'),
('binance_id', '582733976'),
('admin_email', 'atro2829@gmail.com'),
('min_withdrawal', '10'),
('withdrawal_fee', '0');

-- 4. Investment Plans Table
CREATE TABLE investment_plans (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  min_investment DECIMAL NOT NULL,
  duration_days INTEGER NOT NULL,
  profit_percentage DECIMAL NOT NULL,
  color TEXT NOT NULL
);

-- 5. Settings Table
CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Seed Initial Data
INSERT INTO investment_plans (id, name, min_investment, duration_days, profit_percentage, color) VALUES
('starter', 'Starter VIP', 50, 7, 10, 'bg-blue-500'),
('pro', 'Pro VIP', 500, 14, 25, 'bg-indigo-600'),
('elite', 'Elite VIP', 2000, 30, 60, 'bg-emerald-600'),
('whale', 'Whale VIP', 10000, 90, 200, 'bg-amber-500')
ON CONFLICT (id) DO NOTHING;

INSERT INTO settings (key, value) VALUES
('usdt_address', 'TF3kH28vsP7we5LKk7VoUjh1jZfyXXWCQr'),
('binance_id', '582733976'),
('admin_email', 'atro2829@gmail.com')
ON CONFLICT (key) DO NOTHING;
